---
permalink: legal-notices.html 
sidebar: sidebar 
keywords:  
summary:  
---
= Note legali
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le note legali forniscono l'accesso a dichiarazioni di copyright, marchi, brevetti e altro ancora.



== Copyright

http://www.netapp.com/us/legal/copyright.aspx[]



== Marchi

NETAPP, il logo NETAPP e i marchi elencati nella pagina dei marchi NetApp sono marchi di NetApp, Inc. Altri nomi di società e prodotti potrebbero essere marchi dei rispettivi proprietari.

http://www.netapp.com/us/legal/netapptmlist.aspx[]



== Brevetti

Un elenco aggiornato dei brevetti di proprietà di NetApp è disponibile all'indirizzo:

https://www.netapp.com/us/media/patents-page.pdf[]



== Direttiva sulla privacy

https://www.netapp.com/us/legal/privacypolicy/index.aspx[]



== Open source

I file di avviso forniscono informazioni sul copyright e sulle licenze di terze parti utilizzate nel software NetApp.

* link:media/notice-aws.pdf["Avviso per il mediatore Cloud Volumes ONTAP 9.12.1 in AWS"^]
* link:media/notice-google-cloud.pdf["Avviso per il mediatore Cloud Volumes ONTAP 9.12.1 in Google Cloud"^]
* https://docs.netapp.com/us-en/ontap/reference_legal_notices.html#open-source["Avviso per ONTAP"^]

