---
settings:
  name: Cloud Volumes ONTAP
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  versions:
  - version-number: 9.15.1
    url: "/cloud-volumes-ontap-relnotes"
  - version-number: 9.15.0
    url: "/cloud-volumes-ontap-9150-relnotes"
  - version-number: 9.14.1
    url: "/cloud-volumes-ontap-9141-relnotes"
  - version-number: 9.14.0
    url: "/cloud-volumes-ontap-9140-relnotes"
  - version-number: 9.13.1
    url: "/cloud-volumes-ontap-9131-relnotes"
  - version-number: 9.13.0
    url: "/cloud-volumes-ontap-9130-relnotes"
  - version-number: 9.12.1
    url: "/cloud-volumes-ontap-9121-relnotes"
  - version-number: 9.12.0
    url: "/cloud-volumes-ontap-9120-relnotes"
  - version-number: 9.11.1
    url: "/cloud-volumes-ontap-9111-relnotes"
  - version-number: 9.11.0
    url: "/cloud-volumes-ontap-9110-relnotes"
  - version-number: 9.10.1
    url: "/cloud-volumes-ontap-9101-relnotes"
  - version-number: 9.10.0
    url: "/cloud-volumes-ontap-9100-relnotes"
  - version-number: 9.9.1
    url: "/cloud-volumes-ontap-991-relnotes"
  - version-number: 9.9.0
    url: "/cloud-volumes-ontap-990-relnotes"
  - version-number: '9.8'
    url: "/cloud-volumes-ontap-98-relnotes"
  - version-number: '9.7'
    url: "/cloud-volumes-ontap-97-relnotes"
  - version-number: '9.6'
    url: "/cloud-volumes-ontap-96-relnotes"
  - version-number: '9.5'
    url: "/cloud-volumes-ontap-95-relnotes"
  - version-number: '9.4'
    url: "/cloud-volumes-ontap-94-relnotes"
  - version-number: '9.3'
    url: "/cloud-volumes-ontap-93-relnotes"
  langs: it-it,us-en,de-de,es-es,fr-fr,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Note sulla versione di Cloud Volumes ONTAP 9.15.1
    url: "/index.html"
  - title: Novità
    url: "/reference-new.html"
  - title: Panoramica sulle licenze
    url: "/concept-licensing.html"
  - title: Configurazioni supportate
    entries:
    - title: AWS
      url: "/reference-configs-aws.html"
    - title: Azure
      url: "/reference-configs-azure.html"
    - title: Google Cloud
      url: "/reference-configs-gcp.html"
  - title: Limiti di storage
    entries:
    - title: AWS
      url: "/reference-limits-aws.html"
    - title: Azure
      url: "/reference-limits-azure.html"
    - title: Google Cloud
      url: "/reference-limits-gcp.html"
  - title: Problemi noti
    url: "/reference-issues.html"
  - title: Limitazioni note
    entries:
    - title: Limitazioni comuni
      url: "/reference-limitations.html"
    - title: Limitazioni in AWS
      url: "/reference-limitations-aws.html"
    - title: Limitazioni in Azure
      url: "/reference-limitations-azure.html"
    - title: Limitazioni di Google Cloud
      url: "/reference-limitations-gcp.html"
  - title: Integrazioni dei cloud provider
    url: "/reference-provider-integrations.html"
  - title: Note legali
    url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: bluexp-family
