---
sidebar: sidebar 
permalink: reference-configs-aws.html 
keywords: ec2, instance, type, explore, standard, premium, byol, capacity, maximum, virtual machine, Cloud Volumes ONTAP, supported, configurations, sizes, disks, networking, bandwidth, professional package 
summary: In AWS sono supportate diverse configurazioni Cloud Volumes ONTAP. 
---
= Configurazioni supportate per Cloud Volumes ONTAP in AWS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
In AWS sono supportate diverse configurazioni Cloud Volumes ONTAP.



== Numero di nodi supportati

Cloud Volumes ONTAP è disponibile in AWS come sistema a nodo singolo e come coppia di nodi ad alta disponibilità (ha) per la fault tolerance e le operazioni senza interruzioni.

L'aggiornamento di un sistema a nodo singolo a una coppia ha non è supportato. Se si desidera passare da un sistema a nodo singolo a una coppia ha, è necessario implementare un nuovo sistema e replicare i dati dal sistema esistente al nuovo sistema.



== Storage supportato

Cloud Volumes ONTAP supporta diversi tipi di dischi EBS e lo storage a oggetti S3 per il tiering dei dati. La capacità massima dello storage è determinata dalla licenza scelta.



=== Supporto dello storage tramite licenza

Ogni licenza supporta una diversa capacità massima del sistema. La capacità massima del sistema include lo storage basato su disco e lo storage a oggetti utilizzato per il tiering dei dati. NetApp non supporta il superamento di questo limite.

[role="tabbed-block"]
====
.Licenze basate sulla capacità
--
[cols="h,d,d"]
|===
|  | Freemium | Licenza basata sulla capacità 


 a| 
*Capacità massima del sistema* (dischi + storage a oggetti) ^1^
| 500 GiB | 2 PIB ^2^ 


 a| 
*Tipi di disco supportati*
 a| 
* SSD per uso generico (GP3 e GP2) ^3^,^5^
* SSD IOPS (io1) ^3^ con provisioning
* HDD ottimizzato per il throughput (st1) ^4^




 a| 
*Cold data tiering a S3*
 a| 
Supportato

|===
Note:

. Per una coppia ha, il limite di capacità è per l'intera coppia ha. Non è per nodo. Ad esempio, se si utilizza la licenza Premium, è possibile avere fino a 368 TIB di capacità tra entrambi i nodi.
. Per alcune configurazioni, i limiti dei dischi impediscono di raggiungere il limite di capacità utilizzando solo i dischi. In questi casi, è possibile raggiungere il limite di capacità di https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["tiering dei dati inattivi sullo storage a oggetti"^]. Per informazioni sui limiti dei dischi, fare riferimento a. link:reference-limits-aws.html["limiti di storage"].
. Le performance di scrittura migliorate sono abilitate quando si utilizzano SSD con tutte le configurazioni Cloud Volumes ONTAP.
. Si sconsiglia di eseguire il tiering dei dati sullo storage a oggetti quando si utilizzano HDD ottimizzati per il throughput (st1).
. Le configurazioni Cloud Volumes ONTAP nelle zone locali di AWS supportano solo il tipo di disco SSD General Purpose (GP2).


--
.Licenze basate su nodo
--
[cols="h,d,d,d,d"]
|===
|  | ESPLORAZIONE DI PAYGO | Standard PAYGO | PAYGO Premium | BYOL basato su nodo 


| Capacità massima del sistema (dischi + storage a oggetti) | 2 TIB | 10 TIB | 368 TIB ^2^ | 368 TIB per licenza ^2^ 


| Tipi di dischi supportati  a| 
* SSD per uso generico (GP3 e GP2) ^3^,^5^
* SSD IOPS (io1) ^3^ con provisioning
* HDD ottimizzato per il throughput (st1) ^4^




| Tiering dei dati a freddo in S3 | Non supportato 3+| Supportato 
|===
Note:

. Per una coppia ha, il limite di capacità è per l'intera coppia ha. Non è per nodo. Ad esempio, se si utilizza la licenza Premium, è possibile avere fino a 368 TIB di capacità tra entrambi i nodi.
. Per alcune configurazioni, i limiti dei dischi impediscono di raggiungere il limite di capacità utilizzando solo i dischi. In questi casi, è possibile raggiungere il limite di capacità di https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["tiering dei dati inattivi sullo storage a oggetti"^]. Per informazioni sui limiti dei dischi, fare riferimento a. link:reference-limits-aws.html["limiti di storage"].
. Le prestazioni di scrittura migliorate sono abilitate quando si utilizzano SSD con tutte le configurazioni Cloud Volumes ONTAP, ad eccezione DI PAYGO Explore.
. Si sconsiglia di eseguire il tiering dei dati sullo storage a oggetti quando si utilizzano HDD ottimizzati per il throughput (st1).
. Le configurazioni Cloud Volumes ONTAP nelle zone locali di AWS supportano solo il tipo di disco SSD General Purpose (GP2).


--
====


=== Dimensioni dei dischi supportate

In AWS, un aggregato può contenere fino a 6 dischi delle stesse dimensioni. Tuttavia, se si dispone di una configurazione che supporta la funzione Amazon EBS Elastic Volumes, un aggregato può contenere fino a 8 dischi. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-aws-elastic-volumes.html["Scopri di più sul supporto per volumi elastici"^]

[cols="3*"]
|===
| SSD per impieghi generali (gp3 e gp2) | SSD IOPS con provisioning (io1) | HDD ottimizzati per il throughput (st1) 


 a| 
* 100 GiB
* 500 GiB
* 1 TIB
* 2 TIB
* 4 TIB
* 6 TIB
* 8 TIB
* 16 TIB

 a| 
* 100 GiB
* 500 GiB
* 1 TIB
* 2 TIB
* 4 TIB
* 6 TIB
* 8 TIB
* 16 TIB

 a| 
* 500 GiB
* 1 TIB
* 2 TIB
* 4 TIB
* 6 TIB
* 8 TIB
* 16 TIB


|===


== Calcolo EC2 supportato

Ogni licenza Cloud Volumes ONTAP supporta diversi tipi di istanze EC2. Per comodità, la tabella seguente mostra la vCPU, la RAM e la larghezza di banda per ciascun tipo di istanza supportato. https://aws.amazon.com/ec2/instance-types/["Fare riferimento ad AWS per i dettagli più recenti e completi sui tipi di istanze EC2"^].

Cloud Volumes ONTAP può essere eseguito su un'istanza di EC2 riservata o on-demand. Le soluzioni che utilizzano altri tipi di istanze non sono supportate.

Le larghezze di banda mostrate nella tabella seguente corrispondono ai limiti AWS documentati per ciascun tipo di istanza. Questi limiti non si allineano completamente con ciò che Cloud Volumes ONTAP è in grado di offrire. Per le prestazioni previste, fare riferimento alla https://www.netapp.com/pdf.html?item=/media/9088-tr4383pdf.pdf["Report tecnico di NetApp 4383: Caratterizzazione delle performance di Cloud Volumes ONTAP nei servizi Web Amazon con carichi di lavoro delle applicazioni"^].

[cols="8*"]
|===
| Licenza | Istanza supportata | VCPU | RAM | Flash cache ^1^ | Larghezza di banda della rete (Gbps) | Larghezza di banda EBS (Mbps) | Elevata velocità di scrittura ^2^ 


| *Explore o qualsiasi altra licenza* | m5.xlarge ^6^ | 4 | 16 | Non supportato | Fino a 10 | Fino a 4,750 | Supportato (solo nodo singolo) 


.3+| *Standard o qualsiasi altra licenza* | r5.xlarge ^6^ | 4 | 32 | Non supportato | Fino a 10 | Fino a 4,750 | Supportato (solo nodo singolo) 


| m5a.2xlarge | 8 | 32 | Non supportato | Fino a 10 | Fino a 2,880 | Supportato 


| m5,2xlarge ^6^ | 8 | 32 | Non supportato | Fino a 10 | Fino a 4,750 | Supportato 


.22+| *Premium o qualsiasi altra licenza* | m5n.2xlarge | 8 | 32 | Non supportato | Fino a 25 | Fino a 4,750 | Supportato 


| r5,2xlarge ^6^ | 8 | 64 | Non supportato | Fino a 10 | Fino a 4,750 | Supportato 


| r5d.2xlarge | 8 | 64 | Supportato | Fino a 10 | Fino a 4,750 | Supportato 


| c5d.4xlarge ^6^ | 16 | 32 | Supportato | Fino a 10 | 4,570 | Supportato 


| m5,4xlarge ^6^ | 16 | 64 | Non supportato | Fino a 10 | 4,750 | Supportato 


| m5dn.4xlarge | 16 | 64 | Supportato | Fino a 25 | 4,750 | Supportato 


| m5d.8xlarge | 32 | 128 | Supportato | 10 | 6,800 | Supportato 


| r5.8xlarge | 32 | 256 | Non supportato | 10 | 6,800 | Supportato 


| c5.9xlarge | 36 | 72 | Non supportato | 10 | 9,500 | Supportato 


| c5d.9xlarge | 36 | 72 | Supportato | 10 | 9,500 | Supportato 


| c5n.9xlarge | 36 | 96 | Non supportato | 50 | 9,500 | Supportato 


| c5a.12xlarge | 48 | 96 | Non supportato | 12 | 4,750 | Supportato 


| c5.18xlarge | 64 ^4^ | 144 | Non supportato | 25 | 19,000 | Supportato 


| c5d.18xlarge | 64 ^4^ | 144 | Supportato | 25 | 19,000 | Supportato 


| m5d.12xlarge | 48 | 192 | Supportato | 12 | 9,500 | Supportato 


| m5dn.12xlarge | 48 | 192 | Supportato | 50 | 9,500 | Supportato 


| c5n.18xlarge | 64 ^4^ | 192 | Non supportato | 100 | 19,000 | Supportato 


| m5a.16xlarge | 64 | 256 | Non supportato | 12 | 9,500 | Supportato 


| m5.16xlarge | 64 | 256 | Non supportato | 20 | 13,600 | Supportato 


| r5.12xlarge ^3^ | 48 | 384 | Non supportato | 10 | 9,500 | Supportato 


| m5dn.24xlarge | 64 ^4^ | 384 | Supportato | 100 | 19,000 | Supportato 


| m6id.32xlarge | 64 ^4^ | 512 | Supportato | 50 | 40,000 | Supportato 
|===
. Alcuni tipi di istanze includono lo storage NVMe locale, utilizzato da Cloud Volumes ONTAP come _Flash cache_. Flash cache accelera l'accesso ai dati attraverso il caching intelligente in tempo reale dei dati utente recentemente letti e dei metadati NetApp. È efficace per i carichi di lavoro a lettura intensiva, inclusi database, e-mail e file service. La compressione deve essere disattivata su tutti i volumi per sfruttare i miglioramenti delle prestazioni di Flash cache. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-flash-cache.html["Scopri di più su Flash cache"^].
. Cloud Volumes ONTAP supporta un'elevata velocità di scrittura con la maggior parte dei tipi di istanze quando si utilizza una coppia ha. L'elevata velocità di scrittura è supportata con tutti i tipi di istanze quando si utilizza un sistema a nodo singolo. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-write-speed.html["Scopri di più sulla scelta della velocità di scrittura"^].
. Il tipo di istanza r5.12xlarge presenta un limite noto per la supportabilità. Se un nodo si riavvia inaspettatamente a causa di un panico, il sistema potrebbe non raccogliere i file principali utilizzati per la risoluzione dei problemi e causare il problema. Il cliente accetta i rischi e i termini di supporto limitati e si assume la responsabilità del supporto in caso di questa condizione. Questa limitazione riguarda le coppie ha e ha recentemente implementate, aggiornate dal 9.8. La limitazione non riguarda i sistemi a nodo singolo appena implementati.
. Sebbene questi tipi di istanze EC2 supportino più di 64 vCPU, Cloud Volumes ONTAP supporta solo fino a 64 vCPU.
. Quando si sceglie un tipo di istanza EC2, è possibile specificare se si tratta di un'istanza condivisa o dedicata.
. Le zone locali AWS sono supportate nelle seguenti famiglie di tipi di istanza EC2 con dimensioni da xlarge a 4XLarge: M5, C5, C5d, R5 e R5d. link:https://aws.amazon.com/about-aws/global-infrastructure/localzones/features/?nc=sn&loc=2["Fai riferimento ad AWS per i dettagli più recenti e completi sui tipi di istanze EC2 supportati nelle zone locali"^].
+
L'elevata velocità di scrittura non è supportata con questi tipi di istanze nelle zone locali di AWS.





== Regioni supportate

Per il supporto regionale AWS, vedere https://bluexp.netapp.com/cloud-volumes-global-regions["Cloud Volumes Global Regions"^].
