---
sidebar: sidebar 
permalink: reference-new.html 
keywords: 'what"s new, new, features, release notes, enhancements' 
summary: Cloud Volumes ONTAP 9.14.1 include un nuovo miglioramento. 
---
= Novità di Cloud Volumes ONTAP 9.14.1
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP 9.14.1 include nuovi miglioramenti.

Ulteriori funzionalità e miglioramenti sono stati introdotti anche nelle ultime versioni di BlueXP. Vedere https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html["Note di rilascio di BlueXP"^] per ulteriori informazioni.



== 9.14.1 RC1 (6 dicembre 2023)

La Release Candidate 1 di Cloud Volumes ONTAP 9.14.1 è ora disponibile in AWS, Azure e Google Cloud.



== Note sull'aggiornamento

Leggi queste note per ulteriori informazioni sull'aggiornamento a questa release.



=== Come eseguire l'upgrade

Gli aggiornamenti di Cloud Volumes ONTAP devono essere completati da BlueXP. Non aggiornare Cloud Volumes ONTAP utilizzando Gestione di sistema o l'interfaccia CLI. In questo modo si può influire sulla stabilità del sistema.

link:http://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-updating-ontap-cloud.html["Scopri come eseguire l'aggiornamento quando BlueXP ti notifica"^].



=== Percorso di upgrade supportato

È possibile eseguire l'aggiornamento a Cloud Volumes ONTAP 9.14.1 dalle versioni 9.13.1 e 9.14.0. BlueXP richiederà di aggiornare i sistemi Cloud Volumes ONTAP idonei a questa versione.



=== Versione richiesta del connettore

Il connettore BlueXP deve eseguire la versione 3.9.27 o successiva per implementare nuovi sistemi Cloud Volumes ONTAP 9.14.1 e per aggiornare i sistemi esistenti alla versione 9.14.1.


TIP: Gli aggiornamenti automatici del connettore sono attivati per impostazione predefinita, pertanto dovrebbe essere in esecuzione la versione più recente.



=== Downtime

* L'aggiornamento di un sistema a nodo singolo porta il sistema offline per un massimo di 25 minuti, durante i quali l'i/o viene interrotto.
* L'aggiornamento di una coppia ha è senza interruzioni e l'i/o è ininterrotto. Durante questo processo di aggiornamento senza interruzioni, ogni nodo viene aggiornato in tandem per continuare a fornire i/o ai client.




=== le istanze c4, m4 e r4 non sono più supportate

In AWS, i tipi di istanze c4, m4 e r4 EC2 non sono più supportati con Cloud Volumes ONTAP. Se si dispone di un sistema in esecuzione su un tipo di istanza c4, m4 o r4, è necessario passare a un tipo di istanza nella famiglia di istanze c5, m5 o r5. Non è possibile eseguire l'aggiornamento a questa release fino a quando non si modifica il tipo di istanza.

link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-change-ec2-instance.html["Scopri come modificare il tipo di istanza EC2 per Cloud Volumes ONTAP"^].

Fare riferimento a. link:https://mysupport.netapp.com/info/communications/ECMLP2880231.html["Supporto NetApp"^] per ulteriori informazioni sulla fine della disponibilità e sul supporto per questi tipi di istanze.
