---
sidebar: sidebar 
permalink: reference-limitations-azure.html 
keywords: limitations, ha, azure, pay-as-you-go, paygo, cloud solution provider, vm, flash cache; limitations in HA deployment in MAZ, SAZ, multiple availability xone, single availability zone Azure CVO, PSSDv2, premium SSD v2 limitation in CVO, flash cache limitation in CVO 
summary: Queste limitazioni note sono specifiche di Cloud Volumes ONTAP in Microsoft Azure. 
---
= Limitazioni note per Cloud Volumes ONTAP in Azure
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Le seguenti limitazioni note sono specifiche di Cloud Volumes ONTAP in Microsoft Azure. Verificare anche link:reference-limitations.html["Limitazioni per Cloud Volumes ONTAP in tutti i cloud provider"].



== Limitazioni con l'utilizzo delle estensioni VM di Azure

Cloud Volumes ONTAP non supporta le estensioni delle macchine virtuali (VM) di Azure perché influiscono sulle operazioni di gestione nella console NetApp .  Durante la distribuzione, la Console impedisce l'installazione di estensioni sulle VM. Se le estensioni sono già installate sulle VM Cloud Volumes ONTAP esistenti, contattare il supporto Microsoft Azure per rimuoverle. Per indicazioni, fare riferimento all'articolo della knowledge base (KB) https://kb.netapp.com/Cloud/Cloud_Volumes_ONTAP/Can_Azure_VM_Management_Extensions_be_installed_into_Cloud_Volume_ONTAP["È possibile installare Azure VM Management Extensions in Cloud Volume ONTAP?"^]

A partire dal 14 luglio 2025, NetApp invierà e-mail e ti notificherà nella Console se vengono rilevate estensioni VM sulle tue VM Cloud Volumes ONTAP .



== Limitazioni dei dischi Premium SSD v2 per configurazioni HA

I dischi gestiti Premium SSD v2 presentano le seguenti limitazioni per le distribuzioni ad alta disponibilità (HA) in Azure:

* Non supportato nelle distribuzioni HA in regioni non zonali.
* Non supportato nelle distribuzioni HA su più zone di disponibilità.
* Supportato solo nelle configurazioni HA distribuite all'interno di singole zone di disponibilità.


Per utilizzare Premium SSD v2 Managed Disks con configurazioni Cloud Volumes ONTAP HA, assicurarsi che siano soddisfatti i seguenti requisiti:

* La versione Cloud Volumes ONTAP è 9.15.1 o successiva.
* La distribuzione HA avviene in una singola zona di disponibilità di Azure.
* Le regioni e le zone selezionate supportano i dischi gestiti Premium SSD v2.  Per informazioni sulle regioni supportate, fare riferimento a https://azure.microsoft.com/en-us/explore/global-infrastructure/products-by-region/["Sito Web di Microsoft Azure: prodotti disponibili per regione"^] .


Per ulteriori informazioni, consulta  https://docs.netapp.com/us-en/cloud-volumes-ontap-9151-relnotes/reference-new.html#support-for-premium-ssd-v2-managed-disks-in-azure["Supporto per dischi gestiti Premium SSD v2 in Azure"^] .



== Limitazioni con le implementazioni di ha in singole zone di disponibilità

A partire da Cloud Volumes ONTAP 9.15.1, è possibile distribuire istanze di macchine virtuali (VM) in modalità HA in singole zone di disponibilità (AZ) in Azure. Per informazioni sui criteri che supportano questa funzionalità, fare riferimento a https://docs.netapp.com/us-en/cloud-volumes-ontap-9151-relnotes/reference-new.html#deploy-ha-pairs-in-single-availability-zones-in-azure["Implementa coppie ha in singole zone di disponibilità in Azure"^] .

Se la versione Cloud Volumes ONTAP è precedente alla 9.15.1 o se una di queste condizioni non è soddisfatta, il modello di distribuzione precedente che utilizza i set di disponibilità diventa effettivo. Ciò si applica solo alle configurazioni ha.



== Limitazioni della cache flash

Cloud Volumes ONTAP utilizza lo storage NVMe locale in alcuni tipi di macchine virtuali come _Flash cache_. Notare questa limitazione:

* Il riscaldamento della cache dopo un riavvio non è supportato.




== Limitazioni con le distribuzioni HA

Le coppie HA non sono supportate in alcune regioni.

https://bluexp.netapp.com/cloud-volumes-global-regions["Visualizza l'elenco delle regioni Azure supportate"^].
