---
sidebar: sidebar 
permalink: reference-provider-integrations.html 
keywords: maintenance event, azure maintenance event, cloud provider, issues, support 
summary: Questa pagina descrive come NetApp collabora con i cloud provider per risolvere i problemi che potrebbero insorgere. 
---
= Integrazioni dei cloud provider
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Questa pagina descrive come NetApp collabora con i cloud provider per risolvere i problemi che potrebbero insorgere.



== Best practice per il supporto collaborativo

NetApp si impegna a fornire supporto al Licenziatario e farà tutto il possibile per risolvere i problemi di supporto tecnico per Cloud Volumes ONTAP, se segnalati dal Licenziatario. NetApp e il cloud provider applicabile non hanno alcun obbligo di supporto diretto per il software o l'infrastruttura concessi in licenza.

NetApp ha implementato strumenti per connettersi con i cloud provider applicabili in merito a problemi tecnici dei clienti che potrebbero essere il risultato dei servizi cloud provider applicabili. Tuttavia, Il modo migliore per mantenere un flusso di supporto perfetto consiste nel (i) mantenere un contratto di supporto corrente con NetApp e il cloud provider applicabile e (II) coordinare le riunioni di escalation congiunte con NetApp e il cloud provider applicabile quando si verificano problemi tecnici e il cliente ha bisogno di chiarezza su quali prodotti o servizi stanno causando tali problemi tecnici.



== Eventi di manutenzione di Azure

Microsoft pianifica e annuncia a livello di programmazione gli eventi di manutenzione sulla propria infrastruttura di macchine virtuali Azure che possono influire sulle macchine virtuali Cloud Volumes ONTAP. Questi eventi vengono annunciati 15 minuti prima della finestra di manutenzione.

La gestione speciale degli eventi di manutenzione è supportata per le coppie ha (Cloud Volumes ONTAP High Availability). Per mantenere lo stato delle applicazioni, eseguiamo un takeover preventivo per assegnare priorità alla stabilità, poiché qualsiasi perdita di connettività di oltre 15 secondi disattiverà le funzionalità di failover.

Quando viene annunciata la finestra di manutenzione, il nodo partner del nodo di destinazione esegue un takeover. Una volta completata la manutenzione, viene avviato un giveback. Dopo il giveback, si prevede che la coppia ha torni a uno stato di salute. In caso contrario, contattare il supporto NetApp per assistenza. Si noti che gli eventi di manutenzione sono mirati a una delle macchine virtuali di una coppia ha alla volta, e in genere entrambi i nodi sono mirati in un periodo di tempo relativamente breve.

I client CIFS/SMB che utilizzano condivisioni CIFS Cloud Volumes ONTAP non continuamente disponibili subiranno una perdita di sessione sia quando si verifica un Takeover sia quando l'aggregato utilizzato dalla sessione viene restituita al nodo principale dell'aggregato. Si tratta di un limite imposto dal protocollo CIFS/SMB stesso. I clienti potrebbero voler utilizzare prodotti di terze parti per evitare problemi che potrebbero derivare da takeover e giveback. Per ulteriore assistenza, contatta il supporto NetApp.
