---
sidebar: sidebar 
permalink: reference-limitations-azure.html 
keywords: limitations, ha, azure, pay-as-you-go, paygo, cloud solution provider, vm, flash cache 
summary: Queste limitazioni note sono specifiche di Cloud Volumes ONTAP in Microsoft Azure. 
---
= Limitazioni note per Cloud Volumes ONTAP in Azure
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Le seguenti limitazioni note sono specifiche di Cloud Volumes ONTAP in Microsoft Azure. Verificare anche link:reference-limitations.html["Limitazioni per Cloud Volumes ONTAP in tutti i cloud provider"].



== Limitazioni con l'utilizzo delle estensioni VM di Azure

Cloud Volumes ONTAP non supporta le estensioni delle macchine virtuali (VM) di Azure perché ritardano le operazioni. Dopo la distribuzione di Cloud Volumes ONTAP, BlueXP disabilita periodicamente le estensioni delle VM. Se hai installato queste estensioni nel tuo ambiente di lavoro, contatta il supporto Microsoft Azure per disabilitarle o eliminarle.



== Limitazioni della cache flash

Cloud Volumes ONTAP utilizza lo storage NVMe locale in alcuni tipi di macchine virtuali come _Flash cache_. Notare questa limitazione:

* Il riscaldamento della cache dopo un riavvio non è supportato.




== Limiti delle implementazioni ad alta disponibilità

Le coppie ha (High Availability, alta disponibilità) non sono supportate in alcune regioni.

https://bluexp.netapp.com/cloud-volumes-global-regions["Visualizza l'elenco delle regioni Azure supportate"^].



== Limitazioni con le implementazioni di ha in singole zone di disponibilità

A partire da Cloud Volumes ONTAP 9.15.1, è possibile implementare istanze di macchine virtuali in modalità ha in singole zone di disponibilità (AZS) in Azure. Per informazioni sui criteri di supporto di questa funzione, fare riferimento a https://docs.netapp.com/us-en/cloud-volumes-ontap-9151-relnotes/reference-new.html#deploy-ha-pairs-in-single-availability-zones-on-azure["Implementa coppie ha in singole zone di disponibilità in Azure"^].

Se la versione Cloud Volumes ONTAP è precedente alla 9.15.1 o se una di queste condizioni non è soddisfatta, il modello di distribuzione precedente che utilizza i set di disponibilità diventa effettivo. Ciò si applica solo alle configurazioni ha.
