---
sidebar: sidebar 
permalink: reference-new.html 
keywords: 'what"s new, new, features, release notes, enhancements' 
summary: Cloud Volumes ONTAP 9.17.1 include un nuovo miglioramento. 
---
= Novità di Cloud Volumes ONTAP 9.17.1
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP 9.17.1 è disponibile per la distribuzione e l'aggiornamento in Azure e Google Cloud.



== 9.17.1 RC1 (4 settembre 2025)

Ora puoi utilizzare la Release Candidate 1 di Cloud Volumes ONTAP 9.17.1 per la distribuzione e l'aggiornamento in Azure e Google Cloud. Tuttavia, questa versione non è disponibile per la distribuzione e l'aggiornamento in AWS.



== Note sull'aggiornamento

Leggi queste note per ulteriori informazioni sull'aggiornamento a questa release.



=== Come eseguire l'upgrade

Gli aggiornamenti di Cloud Volumes ONTAP devono essere completati da BlueXP. Non aggiornare Cloud Volumes ONTAP utilizzando Gestione di sistema o l'interfaccia CLI. In questo modo si può influire sulla stabilità del sistema.

link:http://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-updating-ontap-cloud.html["Scopri come eseguire l'aggiornamento quando BlueXP ti notifica"^].



=== Percorso di upgrade supportato

È possibile eseguire l'aggiornamento a Cloud Volumes ONTAP 9.17.1 RC1 dalla versione 9.16.1 in Azure e Google Cloud.  BlueXP ti chiederà di aggiornare i sistemi Cloud Volumes ONTAP idonei a questa versione.


NOTE: Per AWS, non ti verrà richiesto di effettuare questo aggiornamento.  L'aggiornamento a Cloud Volumes ONTAP 9.17.1 RC1 non è supportato in AWS.



=== Downtime

* L'aggiornamento di un sistema a nodo singolo porta il sistema offline per un massimo di 25 minuti, durante i quali l'i/o viene interrotto.
* L'upgrade di una coppia ha non comporta interruzioni e l'i/o rimane ininterrotto. Durante questo processo di upgrade senza interruzioni, ogni nodo viene aggiornato in tandem per continuare a fornire i/o ai client.

